-changeSet:
CREATE TABLE notification_tasks
(
    id        BIGINT generated by default as identity primary key,
    message   TEXT      NOT NULL,
    date_time TIMESTAMP NOT NULL,
    chat_id   BIGINT    NOT NULL
)